### ISSUE TITLE
authors

### ISSUE THREAD

**Issue by svnlto** [BedeGaming/orchestra#1]
Oh, I remember this. I believe I'm on of the authors! Would you mind adding me as one?

**Comment by shapeshed** [comment]
Also when is the release party?

**Comment by svnlto** [comment]
:tada:

**Comment by svnlto** [comment]
it's happening!

**Comment by ahumphreys87** [comment]
@svnlto of course - fancy adding a PR? you can have the honour of being our first :smile:

**Comment by ahumphreys87** [comment]
@svnlto closing this one, feel free to open a PR
