### ISSUE TITLE
lodash vs "native" 

### ISSUE THREAD

**Issue by svnlto** [BedeGaming/orchestra#2]
The following link shows why the lodash dependency in this project is obsolete. If you're already doing everything in ES6, why bother having to track another (external) API. (same is true for Backbone.Cocktail btw.)

https://www.reindex.io/blog/you-might-not-need-underscore/

**Comment by ahumphreys87** [comment]
I'm gonna leave the dependency in there for now. Although we are using ES6, users may not be and lodash is a really useful library for non ES6 apps.

Regarding Backbone.Cocktail - I plan to ditch this when we get mixins built into Marionette, coming in 3.0.0
